BOARD_TAG   = arduino_due_x_dbg
ARDUINO_DIR = /home/jan/build/arduino-1.6.9
MONITOR_PORT = /dev/ttyACM1
USER_LIB_PATH = libraries
ARDUINO_LIBS = AD7176 AD57XX DueTimer ArduinoSCPIParser SPI

include ../Arduino-Makefile/Due.mk

